#ifndef _IOCTL
#define _IOCTL

#define IO_GET_SHAREDMEMORY_ADDR	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_REFERENCE_EVENT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_NEITHER , FILE_ANY_ACCESS) 
#define	IO_RESET_EVENT				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_STOP_MONITOR_EVENT		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_NEITHER , FILE_ANY_ACCESS)
#define IO_SET_FILTER				CTL_CODE(FILE_DEVICE_UNKNOWN, 0X805, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif